/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alpha.consolidation.simulator;

import java.util.List;
import java.util.Optional;
import java.util.ArrayList;

import picocli.CommandLine;
import picocli.CommandLine.Option;
import picocli.CommandLine.Command;

import alpha.consolidation.simulator.types.Action;
import alpha.consolidation.simulator.types.State;

@Command(description = "Simulate a VNF Consolidation Scenario", mixinStandardHelpOptions = true, version = "0.0.1")
public class App implements Runnable {
  @Option(names = { "-f", "--file" }, description = "Path of topology file")
  static String file_path;
  @Option(names = { "-a",
      "--algorithm" }, description = "Algorithm to use", required = false, defaultValue = "RANDOM")
  static InferenceAlgorithm algorithm;
  @Option(names = { "-d", "--debug" }, description = "Print debug info", required = false, defaultValue = "false")
  static boolean debug;
  @Option(names = { "-u",
      "--upload" }, description = "Upload results to remote DB", required = false, defaultValue = "false")
  static boolean upload;
  final static List<State> states = new ArrayList<>();
  final static List<Action> actions = new ArrayList<>();

  public void run() {
    Env env = new Env(file_path);
    State state = env.reset();
    Agent agent = new Agent();

    // Run Simulation.
    // for (int i = 1; i < Constants.MAX_EPISODE_LEN; ++i) { (TODO: Change)
    for (int i = 1; i < 5; ++i) {
      Optional<Action> action = agent.inference(state, algorithm);
      if (!action.isPresent())
        break;
      states.add(state);
      actions.add(action.get());
      state = env.step(action.get());
    }
    states.add(state);

    // Print Debug Info.
    if (debug) {
      for (int i = 0; i < actions.size(); ++i) {
        System.out.printf(
            "Episode: %d, State: %s, Action: %s%n",
            i + 1,
            states.get(i).toString(),
            actions.get(i).toString());
      }
      System.out.printf("Init State: %s%n", states.get(0).toString());
      System.out.printf("Final State: %s%n", state.toString());
    }

    // Upload results to remote DB.
    if (upload) {
      System.out.println("Saving results to remote DB...");
    }
  }

  public static void main(String[] args) {
    new CommandLine(new App()).execute(args);
  }
}
