/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alpha.consolidation.simulator;

import java.util.List;
import java.util.Optional;
import java.util.ArrayList;

import picocli.CommandLine;
import picocli.CommandLine.Option;
import picocli.CommandLine.Command;

import alpha.consolidation.simulator.types.Action;
import alpha.consolidation.simulator.types.State;
import alpha.consolidation.simulator.utils.Constants;
import alpha.consolidation.simulator.utils.RandomSingleton;

@Command(description = "Simulate a VNF Consolidation Scenario", mixinStandardHelpOptions = true, version = "0.0.1")
public class App implements Runnable {
  @Option(names = { "-s", "--srv_n" }, description = "Number of servers", defaultValue = "0")
  static int srvNum;
  @Option(names = { "-v", "--vnf_n" }, description = "Number of VNFs", defaultValue = "0")
  static int vnfNum;
  @Option(names = { "-f", "--sfc_n" }, description = "Number of SFCs", defaultValue = "0")
  static int sfcNum;
  @Option(names = { "-d", "--debug" }, arity = "0..1", description = "Debug mode", defaultValue = "false")
  static boolean debug;
  @Option(names = { "-u",
      "--upload" }, arity = "0..1", description = "Upload results to remote DB", defaultValue = "false")
  static boolean upload;

  public void run() {
    if (srvNum == 0)
      srvNum = RandomSingleton.getInstance().nextInt(Constants.MAX_SRV_NUM + 1);
    if (vnfNum == 0)
      vnfNum = RandomSingleton.getInstance().nextInt(Constants.MAX_VNF_NUM + 1);
    if (sfcNum == 0)
      sfcNum = RandomSingleton.getInstance().nextInt(Constants.MAX_SFC_NUM + 1);

    List<State> states = new ArrayList<>();
    List<Action> actions = new ArrayList<>();
    Env env = new Env(srvNum, sfcNum, vnfNum, null, null, null);
    State state = env.reset();
    Agent agent = new Agent();

    // Run Simulation.
    for (int i = 1; i < Constants.MAX_EPISODE_LEN; ++i) {
      Optional<Action> action = agent.inference(state);
      if (!action.isPresent())
        break;
      states.add(state);
      actions.add(action.get());
      state = env.step(state, action.get());
    }
    states.add(state);

    // Print Debug Info.
    if (debug) {
      for (int i = 0; i < actions.size(); ++i) {
        System.out.printf(
            "Episode: %d, State: %s, Action: %s%n",
            i + 1,
            states.get(i).toString(),
            actions.get(i).toString());
      }
      System.out.printf("Init State: %s%n", states.get(0).toString());
      System.out.printf("Final State: %s%n", state.toString());
    }

    // Upload results to remote DB.
    if (upload) {
      System.out.println("Saving results to remote DB...");
      // TODO: Implement this. (Make JSON format)
    }
    env.getPowerConsumption();
  }

  public static void main(String[] args) {
    new CommandLine(new App()).execute(args);
  }
}
