/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sfc.consolidation.simulator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void alwaysPassingTestMethod() {
    assertTrue(true);
  }
}
