/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sfc.consolidation.simulator;

import java.util.List;
import java.util.Optional;
import java.util.ArrayList;

import picocli.CommandLine;
import picocli.CommandLine.Option;
import picocli.CommandLine.Command;
import sfc.consolidation.simulator.types.Action;
import sfc.consolidation.simulator.types.Info;
import sfc.consolidation.simulator.types.State;
import sfc.consolidation.simulator.utils.ApiSingletone;
import sfc.consolidation.simulator.utils.Constants;

@Command(description = "Simulate a VNF Consolidation Scenario", mixinStandardHelpOptions = true, version = "0.0.1")
public class App implements Runnable {
  @Option(names = { "-f", "--file" }, description = "Path of topology file")
  static String file_path;
  @Option(names = { "-a",
      "--algorithm" }, description = "Algorithm to use", required = false, defaultValue = "FIRST_FIT")
  static InferenceAlgorithm algorithm;
  @Option(names = { "-d", "--debug" }, description = "Print debug info", required = false, defaultValue = "true")
  static boolean debug;
  @Option(names = { "-u",
      "--upload" }, description = "Upload results to remote DB", required = false, defaultValue = "true")
  static boolean upload;
  @Option(names = { "-i",
      "--api-server" }, description = "API Server URL", required = false, defaultValue = Constants.DEFAULT_API_SERVER)
  static String api_server;
  @Option(names = { "-m", "--mode" }, description = "Mode", required = false, defaultValue = "EPISODE")
  static Mode mode;
  @Option(names = { "--id" }, description = "Id of This Simulator", required = false, defaultValue = "-1")
  static String id;
  @Option(names = { "-s", "--state" }, description = "Raw JSON State", required = false)
  static String state;

  final static List<State> states = new ArrayList<>();
  final static List<Action> actions = new ArrayList<>();
  final static List<Info> infos = new ArrayList<>();

  public void run() {
    // 1. setup Singleton
    ApiSingletone.setInstance(api_server);

    // 2. create Environment
    Env env;
    if (file_path != null) {
      env = new Env("file", file_path);
    } else if (state != null) {
      env = new Env("raw", state);
    } else {
      env = new Env(null, null);
    }

    // 3. reset Environment
    State state = env.reset();
    if (!env.getResult().isSuccess()) {
      System.out.println("Failed to initialize Environment.");
      return;
    }
    // 4. create Agent
    Agent agent = new Agent(algorithm);

    // 5. run Simulation.
    if (mode == Mode.EPISODE) {
      for (int i = 1; i <= 10; i++) {
        Optional<Action> action = agent.inference(state);
        if (!action.isPresent()) {
          break;
        } else {
          states.add(state);
          actions.add(action.get());
          state = env.step(action.get());
          infos.add(env.getResult());
        }
      }
    }

    states.add(state);
    actions.add(null);
    infos.add(env.getResult());

    // Print Debug Info.
    if (debug) {
      for (int i = 0; i < actions.size(); ++i) {
        System.out.printf("Step: %d%n", i + 1);
        states.get(i).print();
        if (actions.get(i) != null)
          actions.get(i).print();
        if (infos.get(i) != null)
          infos.get(i).print();
      }
      System.out.println("Initial State:");
      states.get(0).print();
      System.out.println("Final State:");
      state.print();
    }

    // Upload results to remote DB.
    if (upload) {
      System.out.println("Saving results to remote DB...");
      agent.submit(states, actions, infos, mode, id);
    }
    System.out.println("Done...");
  }

  public static void main(String[] args) {
    new CommandLine(new App()).execute(args);
  }
}
